apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-ci-
spec:
  entrypoint: argo-ci
  arguments:
    parameters:
    - name: revision
      value: master
    - name: repo
      value: https://github.com/mataerial/backend.git

  templates:
  - name: argo-ci
    steps:
    - - name: test
        template: gradle-test

    - - name: build
        template: gradle-build

  - name: gradle-test
    inputs:
      artifacts:
      - name: code
        path: /src
        git:
          repo: "{{workflow.parameters.repo}}"
          revision: "{{workflow.parameters.revision}}"
    container:
      image: java:openjdk-8
      command: [sh, -exc]
      args: [./gradlew --no-daemon test]
      workingDir: /src

  - name: gradle-build
    inputs:
      artifacts:
      - name: code
        path: /src
        git:
          repo: "{{workflow.parameters.repo}}"
          revision: "{{workflow.parameters.revision}}"
    container:
      image: java:openjdk-8
      command: [sh, -exc]
      args: [./gradlew --no-daemon build]
      workingDir: /src